name: flutter_crm_app
description: "A CRM application for Century 21 Diamante."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  date_time_picker: ^2.1.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  foundation: ^0.0.5
  fpdart: ^1.1.1
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  intl: ^0.17.0
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
